### ISSUE TITLE
Error initializing Fisher from pyarmored fischgott.py

### ISSUE THREAD

**Issue by Jiarui-Cao** [walkway-project/utils#35]
Error report:
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
Cell In[9], line 16
     12 precision = 2 # look into your data before setting this
     15 # should take 20s 
---> 16 fisher = Fisher(
     17     tradeSource=tradespath, 
     18     snapshotSource=obpath, 
     19     updatesSource=updatepath, 
     20     frequency=stepsize, 
     21     verbose=verbose,
     22     precision=precision
     23 )

File :108, in __init__(self, frequency, updatesSource, tradeSource, snapshotSource, verbose, precision, ob_depth, size_cap, n_workers)

File [~/jupyter/venv/lib/python3.11/site-packages/polars/dataframe/frame.py:7942](https://vscode-remote+ssh-002dremote-002bdent-002etailf7f8d-002ets-002enet.vscode-resource.vscode-cdn.net/home/JCJR/walkway-utils/utils/DataReading/~/jupyter/venv/lib/python3.11/site-packages/polars/dataframe/frame.py:7942), in DataFrame.with_columns(self, *exprs, **named_exprs)
   7794 def with_columns(
   7795     self,
   7796     *exprs: IntoExpr | Iterable[IntoExpr],
   7797     **named_exprs: IntoExpr,
   7798 ) -> DataFrame:
   7799     """
   7800     Add columns to this DataFrame.
   7801 
   (...)
   7940 
   7941     """
-> 7942     return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)

File [~/jupyter/venv/lib/python3.11/site-packages/polars/utils/deprecation.py:100](https://vscode-remote+ssh-002dremote-002bdent-002etailf7f8d-002ets-002enet.vscode-resource.vscode-cdn.net/home/JCJR/walkway-utils/utils/DataReading/~/jupyter/venv/lib/python3.11/site-packages/polars/utils/deprecation.py:100), in deprecate_renamed_parameter..decorate..wrapper(*args, **kwargs)
     95 @wraps(function)
     96 def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
     97     _rename_keyword_argument(
     98         old_name, new_name, kwargs, function.__name__, version
     99     )
--> 100     return function(*args, **kwargs)

File [~/jupyter/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:1787](https://vscode-remote+ssh-002dremote-002bdent-002etailf7f8d-002ets-002enet.vscode-resource.vscode-cdn.net/home/JCJR/walkway-utils/utils/DataReading/~/jupyter/venv/lib/python3.11/site-packages/polars/lazyframe/frame.py:1787), in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, _eager)
   1774     comm_subplan_elim = False
   1776 ldf = self._ldf.optimization_toggle(
   1777     type_coercion,
   1778     predicate_pushdown,
   (...)
   1785     _eager,
   1786 )
-> 1787 return wrap_df(ldf.collect())

ComputeError: strict conversion from `str` to `datetime[μs]` failed for column: time, value(s) ["1640998014239000", "1641056291187000", … "1641073465160000"]; if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`

**Comment by Jiarui-Cao** [comment]
Ran the following script in Jupyter Notebook in Conda environment:
Python version: 3.11.5

`import os`
`pair = "XRPUSDT"`
`data_path = os.environ['DATA_WAREHOUSE']`
`tradespath = os.path.join(data_path, 'trades', pair)`
`obpath = os.path.join(data_path, 'ob_snapshot_50', pair)`
`updatepath = os.path.join(data_path, 'l2_updates', pair)`

`stepsize = 1 # in seconds`
`verbose = True`
`precision = 2 # look into your data before setting this`

`fisher = Fisher(`
`    tradeSource=tradespath,` 
`    snapshotSource=obpath,`
`    updatesSource=updatepath,`
`    frequency=stepsize,` 
`    verbose=verbose,`
`    precision=precision`
`)`

**Comment by Jiarui-Cao** [comment]
Pip3 freeze:

asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
comm @ file:///work/ci_py311/comm_1677709131612/work
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
ipykernel @ file:///croot/ipykernel_1691121631942/work
ipython @ file:///croot/ipython_1694181358621/work
jedi @ file:///work/ci_py311_2/jedi_1679336495545/work
jupyter_client @ file:///croot/jupyter_client_1680171862562/work
jupyter_core @ file:///croot/jupyter_core_1679906564508/work
matplotlib-inline @ file:///work/ci_py311/matplotlib-inline_1676823841154/work
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
mkl-service==2.4.0
nest-asyncio @ file:///work/ci_py311/nest-asyncio_1676823382924/work
numpy @ file:///croot/numpy_and_numpy_base_1695830428084/work/dist/numpy-1.26.0-cp311-cp311-linux_x86_64.whl#sha256=184178a893ff0b5e0cb1b0b7a0dddff49dc91424c4e4a01e29bcb05f27a698a6
packaging @ file:///croot/packaging_1693575174725/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
platformdirs @ file:///croot/platformdirs_1692205439124/work
polars==0.19.12
prompt-toolkit @ file:///work/ci_py311/prompt-toolkit_1676824857154/work
psutil @ file:///work/ci_py311_2/psutil_1679337388738/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
Pygments @ file:///croot/pygments_1684279966437/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pyzmq @ file:///croot/pyzmq_1686601365461/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sortedcontainers==2.4.0
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
tornado @ file:///croot/tornado_1696936946304/work
traitlets @ file:///work/ci_py311/traitlets_1676823305040/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work

**Comment by Jiarui-Cao** [comment]
This is all ran on dent server. @jiale0402

**Comment by jiale0402** [comment]
1. plz post the error report with sc or clockblocks 
2. you are using **incorrect** precision for your chosen pair
<img width="1323" alt="截屏2023-11-01 下午4 17 49" src="https://github.com/walkway-project/utils/assets/55820495/e850edeb-72e6-49d2-98ef-a4b4aac56e7a">
look at your pair's snapshots and investigate the price levels before entering the precision desired


3. ensure your pip freeze file contains package version instead of file reference, it's impossible to tell the pacakge version without this information, hence it's hard to reverse engineer what you see

please change accordingly @Jiarui-Cao

**Comment by Jiarui-Cao** [comment]
Should precision be the precision of price or volume?

**Comment by Jiarui-Cao** [comment]
<img width="1217" alt="Screen Shot 2023-11-01 at 16 38 03" src="https://github.com/walkway-project/utils/assets/109039509/da00cc0e-25d3-48d9-a7f1-a649744dd520">
<img width="1221" alt="Screen Shot 2023-11-01 at 16 38 07" src="https://github.com/walkway-project/utils/assets/109039509/f1d5695e-ceb4-4c8a-8086-ee61b342e063">

**Comment by jiale0402** [comment]
> Should precision be the precision of price or volume?

price

**Comment by Jiarui-Cao** [comment]
These are the ones I explicitly pip installed, I believe the other packages were installed upon conda create
mkl-service==2.4.0
polars==0.19.12
sortedcontainers==2.4.0

**Comment by jiale0402** [comment]
> These are the ones I explicitly pip installed, I believe the other packages were installed upon conda create
> mkl-service==2.4.0
> polars==0.19.12
> sortedcontainers==2.4.0

In this case you are missing several dependencies, please review the dependencies posted in slack
